### GET request to example server
GET http://localhost:8080/restapi/hr/Regions


###
GET http://localhost:8080/restapi/hr/jobs
Content-Type: */*

###
GET http://localhost:8080/restapi/hr/Employees
Content-Type: */*